# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
# Exercise 1
import numpy as np

arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [2]:
# Exercise 2
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [3]:
# Exercise 3
import numpy as np

arr = np.linspace(0, 5, 10)
print(arr)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [4]:
# Exercise 4
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [5]:
# Exercise 5
import numpy as np

random_matrix = np.random.rand(4, 4)
print(random_matrix)


[[0.11130882 0.98282353 0.63180872 0.89598822]
 [0.16735628 0.61340618 0.44538413 0.88294859]
 [0.54382665 0.25707857 0.18413856 0.38175653]
 [0.51371928 0.23076051 0.17835397 0.86122521]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [6]:
# Exercise 6
import numpy as np

arr = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr.shape)



(2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [7]:
# Exercise 7
import numpy as np

arr = np.arange(16)  # or any other 1D array with 16 elements
reshaped_matrix = arr.reshape(4, 4)
print(reshaped_matrix)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [8]:
# Exercise 8
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)


int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [9]:
# Exercise 9
import numpy as np

# Create the array
arr = np.arange(1, 101)

# Find even numbers using boolean indexing
even_numbers = arr[arr % 2 == 0]

print(even_numbers)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [10]:
# Exercise 10
import numpy as np

random_int_matrix = np.random.randint(10, 51, size=(6, 6))
print(random_int_matrix)


[[10 35 27 21 36 33]
 [40 35 19 17 36 42]
 [40 28 48 18 14 19]
 [15 11 39 41 27 20]
 [32 47 20 28 48 35]
 [31 26 37 21 49 17]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [11]:
# Exercise 11
import numpy as np

# Create a 4x4 array
arr = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

# Extract a submatrix, e.g., the 2x2 block from the center
submatrix = arr[1:3, 1:3]

print(submatrix)


[[ 6  7]
 [10 11]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [12]:
# Exercise 12
import numpy as np

arr = np.array([[1, 2, 3],
                 [4, 5, 6]])

total_sum = arr.sum()
print(total_sum)


21



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [13]:
# Exercise 13
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [14]:
# Exercise 14
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [15]:
# Exercise 15
import numpy as np

# Create an array of 20 random integers between 1 and 100
arr = np.random.randint(1, 101, size=20)
print("Array:", arr)

# Find the index of the maximum value
max_index = np.argmax(arr)
print("Index of maximum value:", max_index)
print("Maximum value:", arr[max_index])


Array: [99 36  2 29 91 63 92 95 23  1 48 87 80 76 81 51 58 14 45 49]
Index of maximum value: 0
Maximum value: 99



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [16]:
# Exercise 16
import numpy as np

# Create an array from 0 to 9
arr = np.arange(10)
print("Original array:", arr)

# Reverse the array
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [17]:
# Exercise 17
import numpy as np

# Create two 3x3 matrices
A = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

B = np.array([[9, 8, 7],
               [6, 5, 4],
               [3, 2, 1]])

# Element-wise multiplication
C = A * B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nElement-wise multiplication result:")
print(C)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise multiplication result:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [18]:
# Exercise 18
import numpy as np

# Example 1D array
arr = np.array([1, 2, 3, 4])

# Create diagonal matrix
diag_matrix = np.diag(arr)

print("1D Array:")
print(arr)
print("\nDiagonal Matrix:")
print(diag_matrix)


1D Array:
[1 2 3 4]

Diagonal Matrix:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [19]:
# Exercise 19
import numpy as np

# Create two 2D arrays (matrices)
A = np.array([[1, 2],
               [3, 4]])

B = np.array([[5, 6],
               [7, 8]])

# Matrix multiplication
C = np.dot(A, B)
# Or equivalently:
# C = A @ B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix multiplication result:")
print(C)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix multiplication result:
[[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [20]:
# Exercise 20
import numpy as np

# Example 2D array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])

# Flatten to 1D
flattened = arr_2d.flatten()
# Or equivalently:
# flattened = arr_2d.ravel()

print("2D Array:")
print(arr_2d)
print("\nFlattened 1D Array:")
print(flattened)


2D Array:
[[1 2 3]
 [4 5 6]]

Flattened 1D Array:
[1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [21]:
# Exercise 21
import numpy as np

# Example arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack vertically
stacked = np.vstack((arr1, arr2))

print("Array 1:", arr1)
print("Array 2:", arr2)
print("\nStacked vertically:")
print(stacked)


Array 1: [1 2 3]
Array 2: [4 5 6]

Stacked vertically:
[[1 2 3]
 [4 5 6]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [22]:
# Exercise 22
import numpy as np

# Example arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack vertically
stacked = np.vstack((arr1, arr2))

print("Array 1:", arr1)
print("Array 2:", arr2)
print("\nStacked vertically:")
print(stacked)


Array 1: [1 2 3]
Array 2: [4 5 6]

Stacked vertically:
[[1 2 3]
 [4 5 6]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [23]:
# Exercise 23
import numpy as np

arr = np.arange(9)  # array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Split into 3 equal parts
sub_arrays = np.split(arr, 3)

for i, sub in enumerate(sub_arrays):
    print(f"Sub-array {i}: {sub}")


Sub-array 0: [0 1 2]
Sub-array 1: [3 4 5]
Sub-array 2: [6 7 8]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [24]:
# Exercise 24
import numpy as np

# Generate a 1D array of 10 random floats between 0 and 1
arr = np.random.rand(10)

print("Original array:")
print(arr)

# Round each element to 2 decimal places
rounded_arr = np.round(arr, 2)

print("\nRounded array:")
print(rounded_arr)


Original array:
[0.50266468 0.71662598 0.29153767 0.24687736 0.74200401 0.25971664
 0.84924175 0.30308905 0.88749349 0.0160175 ]

Rounded array:
[0.5  0.72 0.29 0.25 0.74 0.26 0.85 0.3  0.89 0.02]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [25]:
# Exercise 25
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 5, 1, 6])

unique_elements = np.unique(arr)

print("Unique elements:", unique_elements)


Unique elements: [1 2 3 4 5 6]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [26]:
# Exercise 26
import numpy as np

arr = np.array([1, 5, 2, 8, 3, 0, 7])
threshold = 3

# Replace elements less than threshold with threshold value
arr[arr < threshold] = threshold

print(arr)


[3 5 3 8 3 3 7]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [27]:
# Exercise 27
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

cumsum = np.cumsum(arr)
print(cumsum)


[ 1  3  6 10 15]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [28]:
# Exercise 28
import numpy as np

arr = np.array([0, 1, 2, 0, 3, 0, 4])

non_zero_count = np.count_nonzero(arr)
print("Number of non-zero elements:", non_zero_count)


Number of non-zero elements: 4



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [29]:
# Exercise 29
import numpy as np

# Create an array of 10 random integers between 1 and 100
arr = np.random.randint(1, 101, size=10)
print("Original array:", arr)

# Sort the array in ascending order
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)


Original array: [64  5 92 99 38 96 52 34 78 51]
Sorted array: [ 5 34 38 51 52 64 78 92 96 99]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [30]:
# Exercise 30
import numpy as np

# Example 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Row-wise sum (sum along columns)
row_sum = matrix.sum(axis=1)

# Column-wise sum (sum along rows)
col_sum = matrix.sum(axis=0)

print("Matrix:")
print(matrix)
print("\nRow-wise sum:", row_sum)
print("Column-wise sum:", col_sum)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [31]:
# Exercise 31
import numpy as np

# Generate a 3x3 array with random values
arr = np.random.rand(3, 3) * 100  # random values between 0 and 100
print("Original array:")
print(arr)

# Normalize the array: (arr - min) / (max - min)
arr_min = arr.min()
arr_max = arr.max()
normalized_arr = (arr - arr_min) / (arr_max - arr_min)

print("\nNormalized array (values between 0 and 1):")
print(normalized_arr)


Original array:
[[52.84657512 93.72066344 69.22850116]
 [56.31044021 79.14629088 28.78517311]
 [38.61467092 10.89153106 60.94737819]]

Normalized array (values between 0 and 1):
[[0.50652521 1.         0.70430498]
 [0.54834462 0.82404292 0.21603078]
 [0.33470277 0.         0.60432659]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [32]:
# Exercise 32
import numpy as np

# Generate a 3x3 array with random values
arr = np.random.rand(3, 3) * 100  # random values between 0 and 100
print("Original array:")
print(arr)

# Normalize the array: (arr - min) / (max - min)
arr_min = arr.min()
arr_max = arr.max()
normalized_arr = (arr - arr_min) / (arr_max - arr_min)

print("\nNormalized array (values between 0 and 1):")
print(normalized_arr)


Original array:
[[91.51197259 11.16754873 38.35229799]
 [73.11553384 75.69982357 82.2660673 ]
 [96.7784292   7.25516432 28.41505193]]

Normalized array (values between 0 and 1):
[[0.9411722  0.04370243 0.34736371]
 [0.73567882 0.76454606 0.83789284]
 [1.         0.         0.23636188]]



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [33]:
# Exercise 33
import numpy as np

# Example square matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

trace_value = np.trace(matrix)

print("Matrix:")
print(matrix)
print("\nTrace of the matrix:", trace_value)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace of the matrix: 15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [34]:
# Exercise 34
import numpy as np

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:")
print(arr)

# Swap row 0 and row 2
arr[[0, 2]] = arr[[2, 0]]

print("\nArray after swapping row 0 and row 2:")
print(arr)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping row 0 and row 2:
[[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [35]:
# Exercise 35
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Convert to column vector using reshape
col_vector = arr.reshape(-1, 1)

# Or equivalently, using np.newaxis
# col_vector = arr[:, np.newaxis]

print("Original 1D array:")
print(arr)
print("\nColumn vector:")
print(col_vector)


Original 1D array:
[1 2 3 4 5]

Column vector:
[[1]
 [2]
 [3]
 [4]
 [5]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [36]:
# Exercise 36
import numpy as np

# Example 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]])

determinant = np.linalg.det(matrix)

print("Matrix:")
print(matrix)
print("\nDeterminant:", determinant)


Matrix:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant: 0.9999999999999987



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [37]:
# Exercise 37
import numpy as np

# Define a 2x2 matrix
matrix = np.array([[4, 2],
                   [1, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Matrix:")
print(matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors (columns correspond to eigenvalues):")
print(eigenvectors)


Matrix:
[[4 2]
 [1 3]]

Eigenvalues:
[5. 2.]

Eigenvectors (columns correspond to eigenvalues):
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [38]:
# Exercise 38
import numpy as np

# Coefficient matrix
A = np.array([[2, 3],
              [5, 4]])

# Right-hand side vector
b = np.array([8, 13])

# Solve for x and y
solution = np.linalg.solve(A, b)

print("Solution [x, y]:", solution)


Solution [x, y]: [1. 2.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [39]:
# Exercise 39
import numpy as np

# Original array
arr = np.array([10, 20, 30, 40, 50], dtype=float)

# Parameters for Gaussian noise
mean = 0
std_dev = 2  # standard deviation

# Generate Gaussian noise
noise = np.random.normal(mean, std_dev, arr.shape)

# Add noise to original array
noisy_arr = arr + noise

print("Original array:", arr)
print("Gaussian noise:", noise)
print("Noisy array:", noisy_arr)


Original array: [10. 20. 30. 40. 50.]
Gaussian noise: [ 2.83554282  4.1838291  -1.8367682  -0.20142181 -0.75909225]
Noisy array: [12.83554282 24.1838291  28.1632318  39.79857819 49.24090775]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [40]:
# Exercise 40
import numpy as np

# Create a 4x4 matrix
matrix = np.array([[ 1,  2,  3,  4],
                   [ 5,  6,  7,  8],
                   [ 9, 10, 11, 12],
                   [13, 14, 15, 16]])

# Extract diagonal elements
diagonal = np.diag(matrix)

print("Matrix:")
print(matrix)
print("\nDiagonal elements:")
print(diagonal)


Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal elements:
[ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [41]:
# Exercise 41
import numpy as np

# Generate 100 random values between 0 and 100
arr = np.random.rand(100) * 100

print("Original array (first 10 values):")
print(arr[:10])

# Clip values to range [10, 50]
clipped_arr = np.clip(arr, 10, 50)

print("\nClipped array (first 10 values):")
print(clipped_arr[:10])


Original array (first 10 values):
[19.54959138 35.39025896 77.65360439 20.16017909 15.72786289  9.67316284
 31.09089209 23.70755917 19.03797078 23.35294248]

Clipped array (first 10 values):
[19.54959138 35.39025896 50.         20.16017909 15.72786289 10.
 31.09089209 23.70755917 19.03797078 23.35294248]



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [42]:
# Exercise 42
import numpy as np

# Create a 2D array with some negative values
arr = np.array([[ 1, -2,  3],
                [-4,  5, -6],
                [ 7, -8,  9]])

print("Original array:")
print(arr)

# Replace negative values with zero
arr[arr < 0] = 0

print("\nArray after replacing negative values with zero:")
print(arr)


Original array:
[[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]

Array after replacing negative values with zero:
[[1 0 3]
 [0 5 0]
 [7 0 9]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [43]:
# Exercise 43
import numpy as np

# Define two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Inner product (dot product)
inner_product = np.inner(a, b)

# Outer product
outer_product = np.outer(a, b)

print("Array a:", a)
print("Array b:", b)
print("\nInner product:", inner_product)
print("\nOuter product:\n", outer_product)


Array a: [1 2 3]
Array b: [4 5 6]

Inner product: 32

Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [44]:
# Exercise 44
import numpy as np
from scipy.spatial import distance

# Example: 4 points in 2D space
points = np.array([[1, 2],
                   [4, 6],
                   [7, 8],
                   [2, 1]])

# Compute pairwise Euclidean distances
dist_matrix = distance.cdist(points, points, 'euclidean')

print("Pairwise distance matrix:")
print(dist_matrix)


Pairwise distance matrix:
[[0.         5.         8.48528137 1.41421356]
 [5.         0.         3.60555128 5.38516481]
 [8.48528137 3.60555128 0.         8.60232527]
 [1.41421356 5.38516481 8.60232527 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [45]:
# Exercise 45
import numpy as np

# Define data type with named fields
dtype = [('name', 'U10'),  # Unicode string with max length 10
         ('age', 'i4'),    # 4-byte integer
         ('height', 'f4')] # 4-byte float

# Create structured array with sample data
data = np.array([('Alice', 25, 5.5),
                 ('Bob', 30, 6.0),
                 ('Charlie', 22, 5.8)],
                dtype=dtype)

print(data)
print("\nNames:", data['name'])
print("Ages:", data['age'])
print("Heights:", data['height'])


[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 22, 5.8)]

Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 22]
Heights: [5.5 6.  5.8]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [46]:
# Exercise 46
import numpy as np

# Create a 5x5 matrix with random integers between 0 and 9
matrix = np.random.randint(0, 10, size=(5, 5))
print("Matrix:")
print(matrix)

# Flatten the matrix and find unique values and their counts
unique_values, counts = np.unique(matrix, return_counts=True)

print("\nUnique values:", unique_values)
print("Counts:", counts)


Matrix:
[[4 9 1 7 9]
 [1 0 5 9 8]
 [6 4 6 3 9]
 [1 8 8 8 5]
 [1 8 0 6 0]]

Unique values: [0 1 3 4 5 6 7 8 9]
Counts: [3 4 1 2 2 3 1 5 4]



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [47]:
# Exercise 47
import numpy as np

# Generate a random 3x3 array
arr = np.random.rand(3, 3) * 10  # random values scaled up

print("Original array:")
print(arr)

# Calculate the mean of each row (keepdims=True to maintain 2D shape for broadcasting)
row_means = arr.mean(axis=1, keepdims=True)

# Subtract row means from each row
centered_arr = arr - row_means

print("\nRow means:")
print(row_means)

print("\nArray after subtracting row means:")
print(centered_arr)


Original array:
[[0.30898001 1.15490693 1.03751469]
 [4.00455607 4.67725559 5.67577964]
 [0.73005422 9.79649731 8.85926588]]

Row means:
[[0.83380054]
 [4.78586376]
 [6.46193914]]

Array after subtracting row means:
[[-0.52482054  0.32110639  0.20371415]
 [-0.78130769 -0.10860818  0.88991587]
 [-5.73188492  3.33455817  2.39732675]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [48]:
# Exercise 48
import numpy as np

# Create an array of 20 random integers between 0 and 100
arr = np.random.randint(0, 101, size=20)

print("Array:", arr)

# Check if any values are greater than 50
any_greater_than_50 = np.any(arr > 50)

print("\nAny values greater than 50?", any_greater_than_50)


Array: [ 54  97  99  81  42  32  89  95  14  34  54  90  44  41  89  30  21 100
  53  95]

Any values greater than 50? True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [49]:
# Exercise 49
import numpy as np

# Example 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define the window size
window_size = 3

# Calculate the moving average using convolution
moving_avg = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')

print("Original array:", arr)
print(f"\nMoving average with window size {window_size}:")
print(moving_avg)


Original array: [ 1  2  3  4  5  6  7  8  9 10]

Moving average with window size 3:
[2. 3. 4. 5. 6. 7. 8. 9.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [50]:
# Exercise 50
import numpy as np

# Example arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# Calculate Pearson correlation coefficient matrix
corr_matrix = np.corrcoef(x, y)

# Extract the correlation coefficient (off-diagonal element)
pearson_corr = corr_matrix[0, 1]

print("Pearson correlation coefficient:", pearson_corr)


Pearson correlation coefficient: -0.9999999999999999



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [51]:
# Exercise 51
import numpy as np

# Array of angles in radians
radians = np.array([0, np.pi/4, np.pi/2, np.pi])

# Convert to degrees
degrees = np.degrees(radians)

print("Radians:", radians)
print("Degrees:", degrees)


Radians: [0.         0.78539816 1.57079633 3.14159265]
Degrees: [  0.  45.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [52]:
# Exercise 52
import numpy as np

# Create a random array of 10 elements
arr = np.random.rand(10)

print("Array:", arr)

# Calculate variance
variance = np.var(arr)

# Calculate standard deviation
std_dev = np.std(arr)

print("\nVariance:", variance)
print("Standard Deviation:", std_dev)


Array: [0.16188428 0.72441653 0.13490467 0.7626773  0.95348417 0.92895936
 0.65376733 0.33614337 0.41480199 0.0482844 ]

Variance: 0.1017008270148223
Standard Deviation: 0.3189056710295731



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [53]:
# Exercise 53
import numpy as np

# Create a 2D array
arr = np.array([[3, 7, 5],
                [1, 6, 9],
                [4, 8, 2]])

print("Array:")
print(arr)

# Indices of max values along each row (axis=1)
max_indices_row = np.argmax(arr, axis=1)

# Indices of max values along each column (axis=0)
max_indices_col = np.argmax(arr, axis=0)

print("\nIndices of max values along each row:", max_indices_row)
print("Indices of max values along each column:", max_indices_col)


Array:
[[3 7 5]
 [1 6 9]
 [4 8 2]]

Indices of max values along each row: [1 2 1]
Indices of max values along each column: [2 2 1]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [54]:
# Exercise 54
import numpy as np

# Define a 2x2 matrix
matrix = np.array([[4, 7],
                   [2, 6]])

print("Original matrix:")
print(matrix)

# Compute the inverse
inverse_matrix = np.linalg.inv(matrix)

print("\nInverse matrix:")
print(inverse_matrix)


Original matrix:
[[4 7]
 [2 6]]

Inverse matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [55]:
# Exercise 55
import numpy as np

# Generate 10 random values
arr = np.random.rand(10)

print("Original array:")
print(arr)

# Standardize the array
standardized_arr = (arr - arr.mean()) / arr.std()

print("\nStandardized array (mean=0, std=1):")
print(standardized_arr)

# Confirm mean and std
print("\nMean:", standardized_arr.mean())
print("Standard deviation:", standardized_arr.std())


Original array:
[0.78793607 0.22580585 0.0058506  0.73745703 0.42505039 0.96662439
 0.10292727 0.00814577 0.13976035 0.96847226]

Standardized array (mean=0, std=1):
[ 0.94150667 -0.5657548  -1.1555293   0.80615527 -0.03151274  1.42063057
 -0.8952339  -1.14937519 -0.79647192  1.42558534]

Mean: -1.554312234475219e-16
Standard deviation: 1.0



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [56]:
# Exercise 56
import numpy as np

# Define two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise addition
addition = a + b

# Element-wise subtraction
subtraction = a - b

print("Array a:", a)
print("Array b:", b)
print("\nElement-wise addition:", addition)
print("Element-wise subtraction:", subtraction)


Array a: [1 2 3 4]
Array b: [5 6 7 8]

Element-wise addition: [ 6  8 10 12]
Element-wise subtraction: [-4 -4 -4 -4]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [57]:
# Exercise 57
import numpy as np

# Create an array of 10 random values
arr = np.random.rand(10)

print("Array:", arr)

# Find the index of the maximum element
max_index = np.argmax(arr)

print("\nIndex of the maximum element:", max_index)
print("Maximum element:", arr[max_index])


Array: [0.19777853 0.14881816 0.61024888 0.27413148 0.8386343  0.71373585
 0.00300541 0.7752001  0.95343298 0.02977698]

Index of the maximum element: 8
Maximum element: 0.9534329791991254



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [58]:
# Exercise 58
import numpy as np

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:")
print(arr)

# Rotate the array by 90 degrees counter-clockwise
rotated_arr = np.rot90(arr)

print("\nArray rotated by 90 degrees:")
print(rotated_arr)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array rotated by 90 degrees:
[[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [59]:
# Exercise 59
import numpy as np

# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Compute Frobenius norm
fro_norm = np.linalg.norm(matrix, ord='fro')

print("Matrix:")
print(matrix)
print("\nFrobenius norm:", fro_norm)


Matrix:
[[1 2 3]
 [4 5 6]]

Frobenius norm: 9.539392014169456



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [60]:
# Exercise 60
import numpy as np

# Create a 3D array of shape (2, 3, 4)
arr = np.arange(24).reshape(2, 3, 4)

print("Original 3D array:")
print(arr)

# Slice out a subarray:
# Let's slice out the first "layer" (first axis index 0), and rows 1 to 2, columns 0 to 1
subarray = arr[0, 1:3, 0:2]

print("\nSliced subarray:")
print(subarray)


Original 3D array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Sliced subarray:
[[4 5]
 [8 9]]



---